# Generated by Django 3.1.6 on 2021-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'superadmin'), ('user', 'user')], default='user', max_length=100)),
            ],
        ),
    ]
