# Generated by Django 3.2.7 on 2021-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
