# Generated by Django 3.2.7 on 2021-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='lasting',
            field=models.IntegerField(choices=[(1, 'fixed'), (2, 'consumable')], default=1),
        ),
    ]
